first_go/fmea_v_1/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  devise_scope :user do
    authenticated :user do
      root 'users#index'
    end
    unauthenticated :user do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :users

  resources :issues, except: :new

  resources :projects

  resources :projects do
    resources :issues
  end

end

first_go/fmea_v_1/app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_project
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = @user.issues
    @issues.each do |my_issue|
      sev = my_issue.severity_estimate
      detect = my_issue.detection_indicators
      dormancy = my_issue.detection_dormancy_period
      if sev && detect && dormancy
        riskvalue = sev * detect * dormancy
        my_issue.update_column :risk_level, riskvalue
      end
    end
    end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issues = @user.issues
    pp @issues
    @issue = set_issue

    # @issues = Issue.all
    @users = User.all
    @projects = Project.all
  end

  # GET /issues/new
  def new
    # if @project != nil
    @issue = @project.issues.build
  # end

    #
    # @issue = Issue.new
    # @project_id = params["project_id"]
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params['id'])
  end

  # POST /issues
  # POST /issues.json

  def create
    pp params
    pp @project

    @issue = @project.issues.build(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to [@project, @issue], notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_issue
    @issue = Issue.find(params[:id])

    # @issue = @project.issues.find(params[:id])
  end

  def set_user
    # if params[:user_id]
    # @user = User.find(params[:user_id])
    @user = current_user
    pp "^^^^^^^^^Setting user. It is #{@user.firstname}"
    pp @project
    # end
  end

  def set_project
    if params[:project_id]
      @project = @user.projects.find(params[:project_id])
    else
      @message = "You have no issues. That's great. \nCreate a project and then you can register some."
    end

    # if params[:project_id]
    #   @project =
    #   Project.find(params[:project_id])
    # end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def issue_params
    params.require(:issue).permit(:item, :function, :failure, :effect_of_failure, :cause_of_failure, :current_controls, :recommended_actions, :probability_estimate, :severity_estimate, :detection_indicators, :detection_dormancy_period, :risk_level, :further_investigation, :project_id)
  end
end

first_go/fmea_v_1/app/views/issues/_form.html.erb
<%= form_for([@project, @issue]) do |f| %>

<% if @issue.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@issue.errors.count, "error") %>
    prohibited this issue from being saved:</h2>

  <ul>
    <% @issue.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= f.hidden_field :project_id %>

<div class="field">
  <%= f.text_field :item, placeholder: "item" %>
</div>
<div class="field">
  <%= f.text_field :function, placeholder: "function" %>
</div>
<div class="field">
  <%= f.text_field :failure, placeholder: "failure" %>
</div>
<div class="field">
  <%= f.text_field :effect_of_failure, placeholder: "effect of failure" %>
</div>
<div class="field">
  <%= f.text_field :cause_of_failure, placeholder: "cause of failure" %>
</div>
<div class="field">
  <%= f.text_field :current_controls, placeholder: "current controls" %>
</div>
<div class="field">
  <%= f.text_field :recommended_actions, placeholder: "recommended actions" %>
</div>
<div class="field">
  <%= f.number_field :probability_estimate, placeholder: "probability estimate" %>
</div>
<div class="field">
  <%= f.number_field :severity_estimate, placeholder: "severity estimate" %>
</div>
<div class="field">
  <%= f.number_field :detection_indicators, placeholder: "detection indicators" %>
</div>
<div class="field">
  <%= f.number_field :detection_dormancy_period, placeholder: "detection dormancy period" %>
</div>
<div class="field">
  <%= f.number_field :risk_level, placeholder: "risk level" %>
</div>
<div class="field">
  <%= f.text_field :further_investigation, placeholder: "further investigation" %>
</div>

<% if false %>
<div class="field">
  <%= f.text_field :project_id %>
</div>
<% end %>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

first_go/fmea_v_1/app/views/issues/edit.html.erb
<h1>Editing Issue:
  <%= @issue.item %></h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %>
|
<%= link_to 'Back', issues_path %>

first_go/fmea_v_1/app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of issues:
  <%= current_user.firstname %>
  <%= current_user.lastname %>
  <% if false %>
  <%= current_user %>
  <% end %>

</h1>

<div class="message-to-user">
  <% if !current_user.issues.first %>
  <p>
    You have no issues. This is good news indeed.
  </p>
  <p>
    Unless, of course, you actually do have issues.
  </p>
  <p>
    In which case, you have more work to do.
  </p>
  <p>
    First,
    <%= link_to "create a project", new_project_path %>.
  </p>
  <p>
    Then you can start documenting your issues.
  </p>
  <% end %>
</div>

<table>

  <thead>
    <tbody>
      <% @issues.each do |issue| %>
      <tr>
        <th>Item</th>
        <td><%= issue.item %></td>
      </tr>
      <tr>
        <th>Project Owner</th>
        <td>
          <%= @user.firstname %>
          <%= @user.lastname %>
        </td>
      </tr>

      <tr>
        <th>Project Name</th>
        <td><%= issue.project.name %></td>
      </tr>

      <tr>
        <th>Function</th>
        <td><%= issue.function %></td>
      </tr>
      <tr>
        <th>Failure</th>
        <td><%= issue.failure %></td>
      </tr>

      <tr>
        <th>Effect of failure</th>
        <td><%= issue.effect_of_failure %></td>
      </tr>

      <tr>
        <th>Cause of failure</th>
        <td><%= issue.cause_of_failure %></td>

      </tr>

      <tr>
        <th>Current controls</th>

        <td><%= issue.current_controls %></td>

      </tr>

      <tr>
        <th>Recommended actions</th>

        <td><%= issue.recommended_actions %></td>
      </tr>

      <tr>
        <th>Probability estimate</th>
        <td><%= issue.probability_estimate %></td>

      </tr>

      <tr>
        <th>Severity estimate</th>

        <td><%= issue.severity_estimate %></td>
      </tr>

      <tr>
        <th>Detection indicators</th>

        <td><%= issue.detection_indicators %></td>
      </tr>

      <tr>
        <th>Detection dormancy period</th>

        <td><%= issue.detection_dormancy_period %></td>
      </tr>

      <tr>
        <th>Risk level</th>

        <td><%= issue.risk_level %></td>
      </tr>

      <tr>
        <th>Further investigation</th>
        <td><%= issue.further_investigation %></td>
      </tr>

      <tr>
        <td>
          <%= link_to 'Show', issue %>
          <%= link_to 'Edit', edit_issue_path(issue) %>
          <% if !@project %>
          <%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
        <td></td>

        <% if false %>
        <tr>
          <th colspan="3"></th>
          <td><%= link_to 'Show', issue %></td>
          <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
          <% if !@project %>
          <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>

        </tr>
        <% end %>

        <% end %>
      </tbody>
    </table>

    <br>

    <p>
      <%= @my_variable  %>
    </p>

    <% if false %>
    <%= link_to 'New Issue', new_issue_path %>
    <% end %>

first_go/fmea_v_1/app/views/issues/new.html.erb
<h1>New Issue for Project:
  <% if @project %>
  <%= @project.name %></h1>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', issues_path, class: "link" %>

first_go/fmea_v_1/app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>
    Project:
  </strong>
  <%= @project.name %>
</p>

<p>
  <strong>Issue owner:</strong>
  <%= @users.find(@projects.find(@issue.project_id).user_id).firstname  %>
  <%= @users.find(@projects.find(@issue.project_id).user_id).lastname  %>
</p>

<p>
  <strong>Item:</strong>
  <%= @issue.item %>
</p>

<p>
  <strong>Function:</strong>
  <%= @issue.function %>
</p>

<p>
  <strong>Failure:</strong>
  <%= @issue.failure %>
</p>

<p>
  <strong>Effect of failure:</strong>
  <%= @issue.effect_of_failure %>
</p>

<p>
  <strong>Cause of failure:</strong>
  <%= @issue.cause_of_failure %>
</p>

<p>
  <strong>Current controls:</strong>
  <%= @issue.current_controls %>
</p>

<p>
  <strong>Recommended actions:</strong>
  <%= @issue.recommended_actions %>
</p>

<p>
  <strong>Probability estimate:</strong>
  <%= @issue.probability_estimate %>
</p>

<p>
  <strong>Severity estimate:</strong>
  <%= @issue.severity_estimate %>
</p>

<p>
  <strong>Detection indicators:</strong>
  <%= @issue.detection_indicators %>
</p>

<p>
  <strong>Detection dormancy period:</strong>
  <%= @issue.detection_dormancy_period %>
</p>

<p>
  <strong>Risk level:</strong>
  <%= @issue.risk_level %>
</p>

<p>
  <strong>Further investigation:</strong>
  <%= @issue.further_investigation %>
</p>

<p>
  <strong>Project:</strong>
  <%= @issue.project.name %>
  <% if false %>
  <%= @issue.project.id %>
  <% end %>
</p>

<% if false %>
<%= @issue.project_id %>
<% end %>

<%= render 'issues/shared/links' %>