first_go/fmea_v_1/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  devise_scope :user do
    authenticated :user do
      root 'users#index'
    end
    unauthenticated :user do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :users

  resources :issues, except: :new

  resources :projects

  resources :projects do
    resources :issues
  end

end

first_go/fmea_v_1/app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :issues
end

first_go/fmea_v_1/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = @user.projects
    @users = User.all

    @users.each do |u_name|
      puts "Users name is #{u_name.firstname} #{u_name.lastname} "
      puts @users

    end

    @projects.each do |proj|
      puts 'Project name is ' + proj.name
      puts 'Project user ID ' +
        proj.user_id.to_s

      # @user_name = @users.where("id == #{proj.user_id}")
      # puts "User name is " + @user_name.name.to_s
      @user_name = @users.find(proj.user_id).firstname + " " + @users.find(proj.user_id).lastname
      puts "Blob" + @user_name.to_s
      puts "@user_name is " + @user_name.to_s

    end


    @users.each do |blob|
      puts "User ID is #{blob.id}"
      # "&&&&&& Blob is: #{blob.id}"
    end

    # @test_projects = Project.find(1).id
    @projects.each do |proj|
      puts 'Project name is ' + proj.name
      puts 'Project user ID ' +
        proj.user_id.to_s

      # @user_name = @users.where("id == #{proj.user_id}")
      # puts "User name is " + @user_name.name.to_s
      # @user_name = @users.find(proj.user_id).firstname + " " + @users.find(proj.user_id).lastname
      # puts "Blob" + @user_name.to_s
      # puts "@user_name is " + @user_name.to_s


    end

    @all_users = User.all

    @all_users.each do |u_name|
      puts "Users name is #{u_name.firstname} #{u_name.lastname} "
      puts

      # puts @all_users
    end

    # @user = Project.user_id
    # puts "User " + @user

    puts ' *** Projects are projects ' + @projects.to_s

    # pp "test Projects" + @test_projects.to_s
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    # @project = @user.projects.find(params[:id])
    # @project = set_project



    # @project_list = Issue.find_by project_id: @project
    # Issue.find_each do |issue|
    #   pp issue[:item]
    # end

    # pp @project_list[:item]
  end

  # GET /projects/new
  def new
    # @project = Project.new
    @users = User.all
    @project = @user.projects.build

  end

  # GET /projects/1/edit
  def edit
    @users = User.all
  end

  # POST /projects
  # POST /projects.json
  def create
    # @issue = @project.issues.build(issue_params)
    @project = @user.projects.build(project_params)
    # the @user bit above ensures that the new project will be owned by the user. You don't need to pass the user id around beyond what that bit does for you anyway.
    # pp "*****" + project_params.to_s


    # @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    # @project = @user.projects.find(params[:user_id]) if @project
    @project = @user.projects.find(params[:id])

  end


  def set_user
    # if params[:user_id]
      # @user = User.find(params[:user_id])
      @user = current_user
      pp "^^^^^^^^^Setting user. It is #{@user.firstname}"
      pp @project
    # end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name)
    # , :user_id)
  end
end

first_go/fmea_v_1/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<% if @project.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@project.errors.count, "error") %>
    prohibited this project from being saved:</h2>

  <ul>
    <% @project.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <!-- <%= f.label :name %><br> -->
  <%= f.text_field :name, placeholder: "Name your project" %>
</div>

<% if false %>
<div class="field">
  <%= f.label :user_id %><br>
  <%= f.text_field :user_id %>
  <% pp "params are " + params.to_s %>
</div>
<% end %>

<% if false %>
<div class="field">
  <%= f.label :user_id %><br>

  <%= f.text_field :user_id %>
  <% end %>

  <% if false %>
  <%= f.collection_select :user, @users.user_id, User.all, :id, include_blank: true %>
  <% end %>

  <% if false %>
  <% @users.each do |user| %>
  <%= user.firstname %>
  <%= user.id %>
  <% end %>

  <%= @users %>
  <%= options_from_collection_for_select(User.all, :id, :firstname) %>
  <% end %>

  <% if false %>
  <div>
    <%= select_tag "project[user_id]", options_from_collection_for_select(@users, "id", "firstname", include_blank: true)  %>
  </div>
  <% end %>
  <% if false %>
  <div>
    Owner of project is:
    <%= current_user.firstname %>
    <%= params[:owner] %>
  </div>
  <%= f.hidden_field :user_id %>
  <% end %>

  <% pp "params are " + params.to_s %>
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

first_go/fmea_v_1/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>
        User name
      </th>
      <th>
        Blob
      </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>

    <tr>
      <td><%= project.name %></td>
      <td><%= project.user.id %></td>
      <td>
        <%= @users.find(project.user_id).firstname %>
        <%= @users.find(project.user_id).lastname %>
      </td>
      <td>
        <%= link_to 'Add issue', new_project_issue_path(project) %>
      </td>
      <% if false %>
      new_issue_path(@user, param1: 'hello'), method: :post %> link_to "Profile", profile_path(@new_issue.id, param1: 'value1', param2: 'value2'), method: :post

      <% end %>

      <td><%= link_to 'Show', project %></td>
      <td><%= link_to 'Edit', edit_project_path(project) %></td>

      <td>
        <% if !project %>
        <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

first_go/fmea_v_1/app/views/projects/new.html.erb
<h1>New Project for
  <%= current_user.firstname %>
  <%= current_user.lastname %></h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

first_go/fmea_v_1/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Project owner:</strong>
  <%= @project.user.firstname %>
  <%= @project.user.lastname %>
</p>

<p>
  <strong>Project ID:</strong>
  <%= @project.id %>
</p>

<% if Issue.where("project_id": @project.id) != [] %>
<h2>
  Issues within Project:
  <%= @project.name %>
</h2>

<% else %>

<h1>
  Project:
  <%= @project.name %>
  is just getting underway
</h1>

<div class="message-to-user">
  Add some
  <%= link_to "issues", new_project_issue_path(@project) %>
  to
  <%= @project.name %>
</div>

<% end %>

<% Issue.where("project_id": @project.id).find_each do |issue| %>
<% if issue[:item] != "" %>

<p>
  <%= issue[:item] %>
</p>
<% end %>
<% end %>

<%= link_to 'Edit', edit_project_path(@project) %>
|
<%= link_to 'Back', projects_path %>